development:
  adapter: postgres
  host: db
  database: postgres
  user: postgres
  password: postgres

test:
  adapter: postgres
  host: localhost
  database: travis_ci_test
  user: postgres

staging: <%= `heroku config:get DATABASE_URL -a taimai` %>
production: <%= `heroku config:get DATABASE_URL -a taimai-demo` %>
