development:
  adapter: postgres
  host: db
  database: postgres
  user: postgres
  password: postgres

production:
  adapter: postgres
  host: db
  database: postgres
  user: postgres
  password: postgres
